import {
  FaCheck,
  FaEye,
  FaEdit,
  FaTrash,
  FaEyeSlash,
  FaPowerOff,
  FaAngleLeft,
  FaAngleUp,
  FaAngleDown,
  FaAngleRight,
  FaDashcube,
  FaList,
  FaUsers,
  FaUserFriends,
  FaLongArrowAltUp,
  FaLongArrowAltDown,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaPlus,
} from "react-icons/fa";
import { FaGear } from "react-icons/fa6";
import { IoMdMenu, IoMdFemale, IoMdMale } from "react-icons/io";
import { BsThreeDotsVertical } from "react-icons/bs";

export {
  FaDashcube,
  FaCheck,
  FaPlus,
  FaEye,
  FaEdit,
  FaTrash,
  FaEyeSlash,
  FaPowerOff,
  FaAngleLeft,
  FaAngleUp,
  FaAngleDown,
  FaAngleRight,
  FaGear,
  FaList,
  FaUsers,
  FaUserFriends,
  IoMdMenu,
  IoMdFemale,
  IoMdMale,
  FaLongArrowAltUp,
  FaLongArrowAltDown,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  BsThreeDotsVertical as ThDotV,
};
